[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps --no-audit --no-fund"
  NODE_OPTIONS = "--max_old_space_size=4096" 